[workspace]
members = [
    "src/experiments",
    "src/dynamic_shims",
    "src/fuzz-controller",
    "src/ping_pong_sync/ping_service",
    "src/ping_pong_sync/pong_service",  "src/ptrace_interrupt",
]
