[package]
name = "injected_shims"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctor = "0.2.8"
libc = "0.2.154"
shared_memory = "0.12.4"
